### ISSUE TITLE
Invalid package name "$app" (name can only contain URL-friendly characters)

### ISSUE THREAD

**Issue by rhysallister** [oslabs-beta/SvelTable#27]
Greetings, 
trying out sveltable and am getting "Invalid package name "$app" (name can only contain URL-friendly characters)"

[See this repl](https://svelte.dev/repl/1c94131d3d8241268a5b2692408aa7fb?version=3.46.4)

**Comment by moore76sc** [comment]
Hey! Thank you for trying SvelTable out! This issue is related to how we access the local storage in SvelteKit. Our method appears to not work correctly with REPL. We are going to investigate a different route.

**Comment by rhysallister** [comment]
Thanks for your response.

> Hey! Thank you for trying SvelTable out! This issue is related to how we access the local storage in SvelteKit. Our method appears to not work correctly with REPL. We are going to investigate a different route.

So is it that this works with SveltKit only and not plain Svelte right now?

**Comment by moore76sc** [comment]
Yeah, it appears so for now. We are working on changing that :D

**Comment by oneezy** [comment]
I have it working in a [REPL](https://svelte.dev/repl/0424440cb892409da5c70d2245ed3a17?version=3.46.4)

```
<script>
	import SvelTable from 'sveltable';
	let data = [
		{ id: '1', name: 'Justin' },
		{ id: '2', name: 'Jessica' },
		{ id: '3', name: 'Chris' },
		{ id: '4', name: 'Corina' },
		{ id: '5', name: 'Aaron' },
		{ id: '6', name: 'Heather' },
	];
</script>
	
<SvelTable dataSet={data} />
```

**Comment by moore76sc** [comment]
Yeah, I was able to get it to work as well but the table was built with SveltKit in mind and will not work in a sandboxed environment as we use local storage for column sizing persistence.
